### ISSUE TITLE
lollipop version for rpi3

### ISSUE THREAD

**Issue by enochcheng** [RTAndroid/android_device_brcm_rpi3#2]
Hi,

I need a lollipop version for rpi3. Is there a way to have device_brcm_rpi3 build with the lollipop?

Currently I'm trying to use libGLES_android in rpi3 and I am getting SurfaceFlinger error during start-up

E/SurfaceFlinger( 119): hwcomposer module not found
W/SurfaceFlinger( 119): no suitable EGLConfig found, trying a simpler query
F/SurfaceFlinger( 119): no suitable EGLConfig found, giving up
--------- beginning of crash
F/libc ( 121): Fatal signal 6 (SIGABRT), code -6 in tid 121 (surfaceflinger)

Thanks in advance.

Enoch

**Comment by ikalkov** [comment]
May I ask what do you need it for? Everything what worked on Lollipop should continue working with Android N. I think for our project it doesn't make a lot of sense to go one step back. So I'll close this issue.

I saw you have already created a ticked at [peyo's repository](https://github.com/peyo-hd/device_brcm_rpi3/issues/35). Maybe he still has an old branch somewhere. Or you can try asking in the forum: https://groups.google.com/forum/#!forum/android-rpi
