### ISSUE TITLE
Script for video settings

### ISSUE THREAD

**Issue by ikalkov** [RTAndroid/android_device_brcm_rpi3#4]
Idea was born here: ​https://groups.google.com/d/msg/android-rpi/lTYIgqZzazY/RnI5uFk2AQAJ

**Comment by ikalkov** [comment]
After the installation the script should offer different setting and setup the needed resolution in
* /boot/config.txt
* /system/build.prop

**Comment by Mimoja** [comment]
Is this supposed to run on the pi or the host?
Supported modes can be reported using the "tvservice" binary on the pi.

**Comment by ikalkov** [comment]
Is tvservice available on Android? Please read the referenced discussion group. The script is supposed to be executed on the host machine, as wrong video configuration prevents Pi from booting (no way to run it on Pi).

Ideally, the script would be executed after the installation and it should mount the SD card and change the required files as needed.

Following values should be set correctly depending on which device (monitor, TV; HDMI, DVI) is used:
hdmi_drive=1
hdmi_group=2

Possible (tested) modes:
 * hdmi_mode=85 / debug.drm.mode.force=1280x720
 * hdmi_mode=28 / debug.drm.mode.force=1280x800
 * hdmi_mode=83 / debug.drm.mode.force=1600x900
 * hdmi_mode=82 / debug.drm.mode.force=1920x1080

**Comment by Mimoja** [comment]
>>Is tvservice available on Android?
Isn't this our decision? I have no RPi3 to test currently. Therefore i can only report from online research and personal experience.

Maybe a custom CVT would fit us more:
https://www.raspberrypi.org/documentation/configuration/config-txt.md
Strg+F: "Which values are valid for my monitor?"

I think it is incredible easy to misconfigure the display mode, not knowing the group, drive, and mode absolutly correctly, when dealing with a "random" display. I dont know my screens settings now, and would not know how to get them, without a connected device.

Will the pi _always_ boot with a "safe" or "default" resolution like 480p? Maybe using config.txt's "hdmi_safe" ?

**Comment by ikalkov** [comment]
How a binary on the Pi would help you, if the Pi doesn't boot? Android enters a boot loop if the graphics can't initialize correctly. There is no other way as to configure it upon installation. Maybe we can add an app for this in future, but in 99% of all cases people want to change the resolution because it doesn't boot on their device.

Custom CVT is OK for me, if it is easier to implement. The default values are OK for the most of users. But if somebody decides to change it, he/she has to know what he/she is doing.

In the script, you will have to ask the user about the desired settings prior to the configuration. Besides of config.txt, build.prop has to be modified accordingly.

For testing, you can flash the latest RTAndroid image on a SD card and play around. You don't need a Pi to validate your script.

**Comment by Mimoja** [comment]
Okay. So we allow users to do "stupid" things, after warning? That is something i can work with.

**Comment by ikalkov** [comment]
Would be nice to have a list of predefined devices and a way to create an own configuration.
Just an idea:
* Generic Monitor 1280x720
* Generic Monitor 1920x1080
* Raspberry Pi 7" DPI Touchscreen -> hdmi_cvt=800 480 60 6 0 0 0
* Waveshare 7" HDMI Touchscreen -> hdmi_cvt=1024 600 60 6 0 0 0
* Custom CVT

**Comment by ikalkov** [comment]
For certain displays we will also need to append or replace other lines in config.txt, build.prop and init.rc. Maybe we should provide a very generic way for doing so?

**Comment by ikalkov** [comment]
@Mimoja Any progress on this?
