### ISSUE TITLE
Check for installed binaries before starting scripts

### ISSUE THREAD

**Issue by ikalkov** [RTAndroid/android_device_brcm_rpi3#8]
inistall.sh
 - adb -> phablet-tools
- partprobe -> ?

gapps.sh
 - adb -> phablet-tools
 - lzip -> lzip

Examples here: http://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script

**Comment by Mimoja** [comment]
Fixed by #11 and #12
